export const SEASONALITY_MAP: Record<string, string[]> = {
  // ── Fruits ──────────────────────────────────────────────────────────────────
  mango:          ["April", "May", "June"],
  orange:         ["December", "January", "February"],
  apple:          ["September", "October", "November"],
  banana:         ["All"],
  papaya:         ["All"],
  guava:          ["October", "November", "December", "January", "February"],
  pomegranate:    ["February", "March", "July", "August"],           // two seasons
  watermelon:     ["March", "April", "May", "June"],
  muskmelon:      ["March", "April", "May"],
  grapes:         ["February", "March", "April"],
  pineapple:      ["April", "May", "June", "July"],
  litchi:         ["May", "June"],
  jackfruit:      ["April", "May", "June", "July"],
  coconut:        ["All"],
  chickoo:        ["February", "March", "April", "September", "October"], // sapota
  custard_apple:  ["August", "September", "October", "November"],
  jamun:          ["May", "June", "July"],
  amla:           ["October", "November", "December", "January"],
  tamarind:       ["January", "February", "March"],
  pear:           ["August", "September", "October"],
  plum:           ["May", "June", "July"],
  peach:          ["May", "June", "July"],
  strawberry:     ["December", "January", "February", "March"],
  fig:            ["July", "August", "January", "February"],
  mulberry:       ["March", "April", "May"],
  wood_apple:     ["September", "October", "November"],
  starfruit:      ["August", "September", "October"],
  dragon_fruit:   ["July", "August", "September", "October", "November"],
  passion_fruit:  ["June", "July", "August", "September"],
  avocado:        ["June", "July", "August"],
  lime:           ["All"],
  lemon:          ["All"],
  sweet_lime:     ["December", "January", "February", "March"],

  // ── Vegetables ──────────────────────────────────────────────────────────────
  tomato:         ["All"],
  potato:         ["October", "November", "December", "January", "February"],
  onion:          ["November", "December", "January", "February", "March"],
  cauliflower:    ["October", "November", "December", "January", "February"],
  cabbage:        ["October", "November", "December", "January", "February"],
  brinjal:        ["All"],
  okra:           ["March", "April", "May", "June", "July", "August"],
  spinach:        ["October", "November", "December", "January", "February", "March"],
  fenugreek:      ["October", "November", "December", "January", "February"],
  coriander:      ["October", "November", "December", "January", "February", "March"],
  peas:           ["October", "November", "December", "January", "February"],
  carrot:         ["October", "November", "December", "January", "February"],
  radish:         ["October", "November", "December", "January"],
  turnip:         ["October", "November", "December", "January"],
  beetroot:       ["October", "November", "December", "January", "February"],
  bitter_gourd:   ["March", "April", "May", "June", "July", "August"],
  bottle_gourd:   ["March", "April", "May", "June", "July"],
  ridge_gourd:    ["March", "April", "May", "June", "July"],
  snake_gourd:    ["April", "May", "June", "July"],
  pumpkin:        ["October", "November", "February", "March", "April"],
  ash_gourd:      ["January", "February", "March", "April"],
  pointed_gourd:  ["March", "April", "May", "June"],
  ivy_gourd:      ["All"],
  colocasia:      ["July", "August", "September", "October"],
  yam:            ["August", "September", "October", "November"],
  sweet_potato:   ["October", "November", "December", "January"],
  drumstick:      ["February", "March", "April", "May"],
  raw_banana:     ["All"],
  raw_papaya:     ["All"],
  green_chilli:   ["All"],
  capsicum:       ["October", "November", "December", "January", "February"],
  cucumber:       ["March", "April", "May", "June", "July"],
  cluster_beans:  ["June", "July", "August", "September"],
  broad_beans:    ["October", "November", "December", "January"],
  french_beans:   ["October", "November", "December", "January", "February"],
  mushroom:       ["October", "November", "December", "January", "February", "March"],
  lotus_stem:     ["September", "October", "November", "December"],
  raw_mango:      ["February", "March", "April"],
  raw_jackfruit:  ["February", "March", "April", "May"],
  amaranth:       ["All"],
  purslane:       ["July", "August", "September"],

  // ── Cereals & Millets ────────────────────────────────────────────────────────
  rice:           ["October", "November"],
  wheat:          ["March", "April"],
  maize:          ["September", "October", "March", "April"],
  sorghum:        ["September", "October", "March", "April"],        // jowar
  pearl_millet:   ["September", "October"],                          // bajra
  finger_millet:  ["September", "October"],                          // ragi
  foxtail_millet: ["September", "October"],
  barnyard_millet:["September", "October"],
  kodo_millet:    ["September", "October"],
  little_millet:  ["September", "October"],
  proso_millet:   ["September", "October"],
  barley:         ["March", "April"],

  // ── Pulses & Legumes ─────────────────────────────────────────────────────────
  chickpea:       ["February", "March"],                             // chana
  pigeon_pea:     ["October", "November"],                           // tur/arhar
  lentil:         ["February", "March"],                             // masoor
  moong_dal:      ["September", "October", "February", "March"],
  urad_dal:       ["September", "October", "February", "March"],
  soybean:        ["October", "November"],
  groundnut:      ["October", "November", "March", "April"],
  horse_gram:     ["October", "November"],
  cowpea:         ["September", "October"],
  moth_bean:      ["September", "October"],
  field_pea:      ["February", "March"],

  // ── Oilseeds ─────────────────────────────────────────────────────────────────
  mustard:        ["February", "March"],
  sesame:         ["October", "November", "March", "April"],
  sunflower:      ["February", "March", "October", "November"],
  safflower:      ["February", "March"],
  linseed:        ["February", "March"],
  castor:         ["December", "January", "February"],
  niger:          ["October", "November"],

  // ── Spices & Condiments ──────────────────────────────────────────────────────
  turmeric:       ["January", "February", "March"],
  ginger:         ["January", "February", "March"],
  garlic:         ["February", "March", "April"],
  black_pepper:   ["December", "January", "February"],
  cardamom:       ["August", "September", "October", "November"],
  clove:          ["July", "August", "September"],
  cinnamon:       ["All"],
  nutmeg:         ["June", "July", "August"],
  vanilla:        ["May", "June"],
  star_anise:     ["March", "April"],
  fennel:         ["February", "March", "April"],
  cumin:          ["February", "March"],
  coriander_seed: ["February", "March"],
  ajwain:         ["October", "November"],
  dill:           ["October", "November", "December"],
  fenugreek_seed: ["February", "March"],
  red_chilli:     ["December", "January", "February"],

  // ── Plantation Crops ─────────────────────────────────────────────────────────
  tea:            ["March", "April", "May", "October", "November"],
  coffee:         ["December", "January", "February"],
  rubber:         ["All"],
  cashew:         ["February", "March", "April", "May"],
  cocoa:          ["October", "November", "May", "June"],
  arecanut:       ["November", "December", "January"],

  // ── Flowers ──────────────────────────────────────────────────────────────────
  rose:           ["November", "December", "January", "February"],
  marigold:       ["October", "November", "December", "January"],
  jasmine:        ["April", "May", "June", "July", "August"],
  chrysanthemum:  ["October", "November", "December"],
  tuberose:       ["July", "August", "September", "October"],
  lotus:          ["July", "August", "September", "October"],

  // ── Medicinal & Aromatic ─────────────────────────────────────────────────────
  ashwagandha:    ["January", "February"],
  tulsi:          ["All"],
  aloe_vera:      ["All"],
  stevia:         ["All"],
  lemongrass:     ["All"],
  patchouli:      ["All"],
  brahmi:         ["All"],
  neem:           ["All"],
  moringa:        ["February", "March", "April", "May"],
  giloy:          ["All"],
  shatavari:      ["October", "November", "December"],
  kalmegh:        ["September", "October"],
  safed_musli:    ["November", "December"],
  isabgol:        ["February", "March"],                             // psyllium
  senna:          ["October", "November"],
  eucalyptus:     ["All"],

  // ── Sugarcane & Fibres ───────────────────────────────────────────────────────
  sugarcane:      ["October", "November", "February", "March"],
  cotton:         ["October", "November"],
  jute:           ["July", "August", "September"],
};